Asana/developer-docs

source/includes/markdown/_14-how-to-use.html.md

fix layout of triage bot tutorial

---

source/includes/markdown/_13-deprecations.html.md

Cleaning up the deprecations section

Rossgrambo deprecations march 20

---

source/stylesheets/screen.css.scss

In this PR, I added the media css that will render the feedback response as expected.

Add media css to Developer Satisfaction feature

---

source/docs/index.html.md
source/includes/markdown/_05-basic-concepts.html.md
source/includes/markdown/_06-object-hierarchy.html.md
source/includes/markdown/_07-auth.html.md
source/includes/markdown/_07-errors.html.md
source/includes/markdown/_08-rate-limits.html.md
source/includes/markdown/_09-rich-text.html.md
source/includes/markdown/_10-pagination.html.md
source/includes/markdown/_11-input-output-options.html.md
source/includes/markdown/_12-custom-external-data.html.md
source/includes/markdown/_13-deprecations.html.md
source/includes/markdown/_13-publish-your-app.html.md
source/includes/markdown/_13-why-use-asanas-api.html.md
source/includes/markdown/_14-how-to-use.html.md
source/includes/markdown/_15-quick-start.html.md
source/layouts/layout.erb

Jeff schneider branch

---

source/includes/markdown/_06-object-hierarchy.html.md
source/includes/markdown/_07-errors.html.md
source/includes/markdown/_15-quick-start.html.md

Make errors doc top level and make copy edits

---

source/includes/markdown/_13-publish-your-app.html.md
source/includes/markdown/_14-how-to-use.html.md

Jeff schneider add api explorer

---

source/includes/markdown/_14-publish-your-app.html.md

I added a page to the docs for custom apps (i.e. apps built by 2nd party devs).

Publish custom apps documentation

---

source/includes/markdown/_13-platform-ui.html.md

Replace expires field with expires_at

---

defs/ui_hooks_oas.yaml
source/includes/markdown/_07-auth.html.md
source/includes/markdown/_09-rich-text.html.md
source/includes/markdown/_13-platform-ui.html.md
source/includes/markdown/_14-deprecations.html.md
source/includes/markdown/_15-quick-start.html.md
source/includes/ui-hooks-reference/_index.html.md

Updated a few markdown files and a YAML file for:
- _oath_ -> _OAuth_
- _Github_ -> _GitHub_
- _Javascript_ -> _JavaScript_

Update docs content for CamelCase (GitHub, JavaScript, OAuth).

---

source/includes/markdown/_09-rich-text.html.md

Adds defensive / custom handling guidance

Added rich text guidelines

---

source/includes/markdown/_09-rich-text.html.md

Slightly adjusted some rich text guidance

Slightly adjusted some rich text guidance

---

source/includes/markdown/_15-how-to-use.html.md

Update Postman Collection from most recent OpenAPI spec file

Update Postman Collection.

---

source/includes/markdown/_13-platform-ui.html.md
source/includes/ui-hooks-reference/_index.html.md
source/layouts/layout.erb
source/templates/main.dot
source/templates/operation.dot

Update alpha to beta

---

source/includes/markdown/_13-platform-ui.html.md

Add QA checklist

---

source/includes/markdown/_10-pagination.html.md

Update Pagination header.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Update photos property for user.

---

source/javascripts/all_nosearch.js

Changes the content shown for positive feedback submission (i.e., when answering "Yes" to "Was this section helpful?") in docs.

Update feedback button.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Add Time Periods.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Add create Goals. Fix updateGoalMetric.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Fix body parameter for setting a goal metric.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_13-platform-ui.html.md

Add Vimeo to Attachments. Update Resource Search header.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Add `PUT` webhook endpoint

---

source/includes/markdown/_13-platform-ui.html.md

Update App Components closed beta overview

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Update addMembers to a project.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build (9/15/2021)

---

source/includes/markdown/_15-how-to-use.html.md

Update Run in Postman button.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Update Job status enum description.

---

Makefile
defs/asana_oas.yaml
source/docs/index.html.md
source/includes/api-reference/_index.html.md
source/includes/markdown/_15-how-to-use.html.md
source/includes/markdown/_17-audit-log.html.md
source/stylesheets/screen.css.scss

Adds Audit Log API. Updates Postman Collection.

Audit Log API

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_12_1-news-and-changelog.html.md

Update addUser for teams to show TeamMembership response.

---

defs/app_components_oas.yaml
defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_12_1-news-and-changelog.html.md
source/includes/ui-hooks-reference/_index.html.md

Build 11-21-2021.

---

source/includes/markdown/_07-errors.html.md

Update 401 error copy.

---

source/includes/markdown/_13-platform-ui.html.md

Update App Components Authorization section.

---

source/includes/markdown/_13-platform-ui.html.md

Move the copy above the App Components configurations table.

Move App Components config details up.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Aw asana build dec15

---

defs/app_components_oas.yaml
source/includes/ui-hooks-reference/_index.html.md

Add Typeahead to spec.

---

defs/app_components_oas.yaml
defs/asana_oas.yaml
source/includes/ui-hooks-reference/_index.html.md

Build Jan. 6th

---

defs/app_components_oas.yaml
defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/ui-hooks-reference/_index.html.md

Build Jan. 13th.

---

README.md

I just went through the install flow and hit some roadblocks - updated the README to try remove some of them.

Update README.md to fix problems with installation

---

defs/app_components_oas.yaml
defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/ui-hooks-reference/_index.html.md

Build Jan 22nd.

---

source/includes/markdown/_17-audit-log.html.md

- Adds workspace_default_session_duration_changed,  workspace_announcement_created, workspace_announcement_removed events
- Reformats the Admin Settings section to include Resource Type
- Renames AdvancedSearchQuery resource type to Search to match the name used in the API

Add new audit log events

---

source/includes/markdown/_09-rich-text.html.md

Add documentation for the new rich text features that are available
in project briefs (e.g. tables, inline images, etc.).

Enhanced rich text

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_12_1-news-and-changelog.html.md

Add Project Brief API.

---

source/includes/ui-hooks-reference/_index.html.md
source/templates/main.dot
source/templates/operation.dot

Update App Components Overview link for BETA spans.

---

source/includes/api-reference/_index.html.md
source/templates/operation.dot

Add preview banners for Project Brief API endpoints.

---

source/includes/markdown/_13-platform-ui.html.md

Add missing horizontal line break between tags.

---

source/includes/markdown/_13-platform-ui.html.md

Add 'coming soon' messages for the upcoming open beta.

---

source/includes/markdown/_17-audit-log.html.md

- Add documentation for the new attachment uploaded/downloaded Audit Log events

Add attachment audit log events to documentation

---

defs/app_components_oas.yaml
source/includes/ui-hooks-reference/_index.html.md

Update Error schemas for App Components.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_12_1-news-and-changelog.html.md

Build Feb 28 2022

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build March 2nd.

---

source/includes/markdown/_13-platform-ui.html.md

Clarify CORS requirement in App Components docs.

---

source/includes/markdown/_17-audit-log.html.md

Add audit logging for task templates and project templates

Add audit logging for task templates and project templates

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Add new Project Templates endpoints

---

source/includes/markdown/_15-how-to-use.html.md

Update postman collection

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Update Project Templates

---

source/includes/markdown/_13_1-scim.html.md
source/includes/markdown/_17-audit-log.html.md

Add Enterprise disclaimers for Audit Log API and SCIM endpoints.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build March 3, 2022

---

source/includes/markdown/_17-audit-log.html.md

Update user_app_authorized and user_app_revoked resource type to user instead of app

Update user_app_authorized and user_app_revoked resource type to user

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_08-rate-limits.html.md

Changes:
- Standard docs build (to sync the OAS)
- Clarification that Retry-After is in seconds

Build March 16th.

---

source/includes/markdown/_13-platform-ui.html.md

Add signature header details to Message Integrity (App Components).

---

source/includes/markdown/_07-auth.html.md
source/includes/markdown/_13-platform-ui.html.md

Update information regarding the 'state' parameter for OAuth.

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build April 1st 2002 (part 2).

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build April 11th 2022.

---

source/includes/markdown/_13-platform-ui.html.md

- Fix minor grammar mistakes for App Components documentation

Fix minor grammar mistakes for App Components documentation

---

increment_version.js

- Remove updating of `setup.py` and `asana/__init__.py` from increment version script

Update increment_version script for python version bump

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Just a `make full_openapi_sync`

Build April 22nd, 2022

---

source/includes/markdown/_17-audit-log.html.md

Updated audit log docs for Admin App Management 
Asana Task: https://app.asana.com/0/1199874496816286/1201267261535209/f

Updated audit log docs for Admin App Management

---

source/includes/markdown/_13-platform-ui.html.md

Add diary study sign up to AC overview page

---

source/includes/markdown/_17-audit-log.html.md

- workspace_form_is_embeddable_forms_enabled
- workspace_form_is_embeddable_forms_disabled

Add audit log embedded forms enabled disabled

---

source/templates/main.dot

- Add required tag to properties table in main.dot template

Add required tag to properties table in main template

---

source/includes/markdown/_13-platform-ui.html.md

Document App Components hosting options

---

source/includes/markdown/_13-platform-ui.html.md

- Added a troubleshooting section for App Components docs

Add troubleshooting section to App Components doc

---

source/includes/markdown/_13-platform-ui.html.md

- Added links to example App Components Rule Action example app

Add link to example rule actions app

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build June 21st.

---

Makefile
defs/asana_oas.yaml
pull_forum_updates.js
source/includes/api-reference/_index.html.md

- Builds from updated OpenAPI spec
- Fixes `ifndef` indentation error in Makefile
- Comments out automated version bumps for Node, Ruby, and Python
- Updates URL for forum updates

Build June 24th.

---

source/includes/markdown/_12_0-news-and-changelog.html.md
source/includes/markdown/_14-publish-your-app.html.md

- Update broken Platform News link
https://user-images.githubusercontent.com/99784540/176503113-a614efae-e4ad-44f8-bbfc-f0d8c701a081.mov

Update Platform News link

---

defs/app_components_oas.yaml
source/includes/ui-hooks-reference/_index.html.md

- Update value for FormField-Typeahead to TypeaheadItem

Fix value description for formfield typeahead

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

- Update description for events conditional properties

Update conditional properties for events schema

---

defs/app_components_oas.yaml
source/includes/ui-hooks-reference/_index.html.md

- Update example color in widget pill from `gray` to `cool-gray` which is available from the enum options

Update WidgetField-Pill color example data

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

- Update description for webhook reference section

Update description for webhooks reference

---

source/includes/markdown/_18-webhooks.html.md

- Added a security section to webhooks documentation

Add webhook security section

---

source/includes/markdown/_17-audit-log.html.md

Add descriptions of the events workspace_logged_out_view_authentication_required_enabled, workspace_logged_out_view_authentication_required_disabled to audit log docs.

Add audit log events workspace_logged_out_view_authentication_required_enabled, workspace_logged_out_view_authentication_required_disabled

---

defs/app_components_oas.yaml
defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_13-platform-ui.html.md
source/includes/ui-hooks-reference/_index.html.md
source/templates/operation.dot

build using new deploy process

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build docs 08/09/2022

---

source/includes/markdown/_17-audit-log.html.md

Audit log task: https://app.asana.com/0/1200172659753833/1202391537802396/f

Add entry about the workspace_security_contact_email_changed audit log

---

source/includes/markdown/_17-audit-log.html.md

audit log events
https://app.asana.com/0/1201333283899472/1202163354874090
https://app.asana.com/0/1201333283899472/1202163354874100

add portfolio_member_added and portfolio_member_removed new audit log events

---

defs/asana_oas.yaml
source/404.html
source/includes/api-reference/_index.html.md
source/includes/markdown/_13-platform-ui.html.md
source/includes/markdown/_14-deprecations.html.md
source/includes/markdown/_14-publish-your-app.html.md
source/includes/markdown/_15-library-quick-start.html.md
source/javascripts/all_nosearch.js

- Add breaking changes content
- Copy over OpenAPI spec
- Update forum links

Build 9/2/2022

---

source/includes/markdown/_17-audit-log.html.md

Mikephung attachment export audit log

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/markdown/_13-platform-ui.html.md

- Build documentation from the recent OpenAPI spec
- Remove expired link from the App Components content

Build docs. Update App Components link.

---

source/includes/markdown/_17-audit-log.html.md

Add new domain administrative settings audit log - workspace_app_recipient_emails_changed
Audit log Event task: https://app.asana.com/0/1200172659753833/1202991923476057/f 
Asana task: https://app.asana.com/0/1200691334933384/1202393000506839/f

Add new audit log

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

- Build docs 09/28/2022 -> added information about My Tasks

Build docs 09/28/2022

---

source/docs/index.html.md
source/includes/markdown/_01-overview.html.md
source/includes/markdown/_02-object-hierarchy.html.md
source/includes/markdown/_03-auth.html.md
source/includes/markdown/_04-errors.html.md
source/includes/markdown/_05-rate-limits.html.md
source/includes/markdown/_06-rich-text.html.md
source/includes/markdown/_07-pagination.html.md
source/includes/markdown/_08-input-output-options.html.md
source/includes/markdown/_09-custom-external-data.html.md
source/includes/markdown/_10-app-server.html.md
source/includes/markdown/_11_0-news-and-changelog.html.md
source/includes/markdown/_12-audit-log.html.md
source/includes/markdown/_13-scim.html.md
source/includes/markdown/_14-deprecations.html.md

Audit of [Overview](https://developers.asana.com/docs/overview) down to [Deprecations](https://developers.asana.com/docs/deprecations) in the sidebar of docs.
Next PR will cover [Developer Sandbox](https://developers.asana.com/docs/developer-sandbox) to [Official client libraries](https://developers.asana.com/docs/official-client-libraries)

Markdown audit: part 2

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Build October 5th, 2022

---

defs/asana_oas.yaml
source/includes/api-reference/_index.html.md

Document `display_value` on custom_fields can be null

Document CF display_value can be null

---

defs/app_components_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/app-components-reference/_index.html.md
source/templates/main.dot
source/templates/operation.dot

Makes docs from updated OAS. Also includes capitalization updates within dot files.

Build October 10th

---

source/includes/markdown/_app-components.html.md

Use "Everything" code samples from UI builder.

Update code samples for App Components.

---

defs/app_components_oas.yaml
defs/asana_oas.yaml
source/includes/api-reference/_index.html.md
source/includes/app-components-reference/_index.html.md

Build November 22nd, 2022.

---

.github/workflows/build.yml
defs/app_components_oas.yaml
source/includes/app-components-reference/_index.html.md

Build December 5th, 2022

---

.github/workflows/deploy.yml
.github/workflows/dev_deploy.yml
.github/workflows/publish.yml

- Use Ubuntu-20.04 for builds and deploys

Update set ubuntu version on GitHub Actions

---

defs/app_components_oas.yaml
defs/asana_oas.yaml

Pulls latest specs, Incorporates spec changes from these 2 prs:
https://github.com/Asana/codez/pull/174146
https://github.com/Asana/codez/pull/174154

Update specs from codez

---

defs/asana_oas.yaml

see https://github.com/Asana/codez/pull/174294

update oas again

---

source/includes/markdown/_developer-sandbox.html.md

- Update developer sandbox docs

Update developer sandbox doc

---

source/includes/markdown/_audit-log.html.md

Rename domain to workspace

---

defs/asana_oas.yaml

Build OAS 01_23_2023

---

defs/asana_oas.yaml

Build January 25th.

---

source/includes/markdown/_audit-log.html.md

Add story deleted and undeleted events

---

source/explorer/index.html

redirects if not on the correct URL

Legacy redirect refresh
