- source/includes/markdown/_13-deprecations.html.md
> Remove reference to dev newsletter from deprecations page

- source/includes/markdown/_07-auth.html.md
- fix `<a>` parameter that cannot be jumped
- tested at `Chrome Version 83.0.4103.61 (Official Build) (64-bit)`
> Fix page inside link

- source/includes/markdown/_07-auth.html.md
Previously we were linking to a draft of the spec.
The difference between versions of the spec are mostly grammatical.
> Link to real OAuth spec

- source/includes/markdown/_07-auth.html.md
Adds public API documentation on the `/-/oauth_revoke` endpoint which is used to deauthorize refresh and bearer tokens.
cc @jueunlee-asana @kquicho @es2fq
> Add public API docs on oauth_revoke endpoint

- defs/asana_oas.yaml
There is a duplicate enumeration value for the `sticker_name` parameter.
As a result, the auto-generated client code for C# fails.
> Fix duplicate enum value.

- Makefile
- README.md
- defs/app_components_oas.yaml
- source/includes/ui-hooks-reference/_index.html.md
Build commands now include api_explorer as a part of full_openapi_sync. 
If this causes any problems for you feel free to remove it.
> Renames ui-hooks, updating readme, updating build commands

- source/includes/markdown/_13-platform-ui.html.md
Updates the App Components authentication guide to clarify that the event origin is set by the browser, and that the `targetOrigin` of the window.opener.postMessage call must match the Asana URL.
> Clarify origin values in authentication section

- source/includes/markdown/_13-platform-ui.html.md
Attempts to address a common developer pitfall when testing apps by providing instructions on how to manually trigger the installation flow after an app has been installed in a domain for the first time.
> Provide instructions on triggering install flow

- source/includes/markdown/_13-platform-ui.html.md
I made a PR that removes the need for setting a server_url on apps to simplify the authentication process for developers. This PR updates the documentation to reflect that change.
> Update docs to reflect removal of serverUrl

- .github/workflows/build.yml
- pull_forum_updates.js
`pull_forum_updates.js` gets run during `make docs_gen`, but will fail because the old URL redirects. Updating the URL to the redirected URL.
I also changed the build to only run against ruby 2.5 since that's what we actually use
> Update URL to non-redirect version, remove unneeded ruby builds

- source/includes/api-reference/_index.html.md
- source/includes/ui-hooks-reference/_index.html.md
- source/templates/main.dot
- Removes erroneous link for `{siteUrl}` (i.e., it should _not_ be a link)
- Cleans up presentation of terms and support links
-----
Current:
Updated:
> Update API Reference overviews for App Components and core API.

- source/includes/markdown/_17-audit-log.html.md
Tried real hard to make the description useful! It's a bit of a mouthful compared to other events but worth being clear about, I think.
This setting is much like other admin console toggles, but there is a bit of subtlety because the effect in the app is a combination of domain-level and artifact-level requirements, so tried to include that in the description.
Task: https://app.asana.com/0/1200850281178363/1202009752618864/f
> Add audit log events workspace_form_link_authentication_required_enabled, workspace_form_link_authentication_required_disabled

- defs/asana_oas.yaml
- source/includes/api-reference/_index.html.md
- Removes "recipe" references for new Project Template
- Adds `start_at` to Tasks
> Build April 5th, 2022

- source/includes/markdown/_13-platform-ui.html.md
Replaces animated GIF in the Overview of App Components with a video tutorial.
Responsive for desktop/laptop/tablet, but mobile will need to full-screen the video.
> App Components Getting Started Video

- Makefile
This is my guess for why the `api-explorer` updates haven't gone through when running `make full_openapi_sync` - the `api-explorer` repo is never set up locally in the `client_libraries` sibling directory. Adds it to `first_time_setup`.
@aw-asana / @jv-asana if you want to have it set up locally, you can run
```
cd ../client_libraries && git clone git@github.com:Asana/api-explorer.git
```
from your `developer-docs` directory (running `make first_time_setup` might fail since you've already run it)
> Add api-explorer git setup to first time setup

- source/includes/markdown/_13-platform-ui.html.md
- Update value for footer property for widget metadata in example response. This is inconsistent with our documentation for footer value in the widget metadata schema and should be one of the footer objects listed and not a string.
> Update AC widget metadata footer response example

- defs/asana_oas.yaml
- source/includes/api-reference/_index.html.md
- Update description for workspace typeahead to say that results are return for query with empty string value which is the expected behavior not an empty result set
> Update description for workspace typeahead query description

- source/includes/markdown/_13-platform-ui.html.md
- source/includes/markdown/_18-webhooks.html.md
Remove `allowfullscreen` from vimeo iframe as it is not needed according to the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). I tested the docs locally and was able to fullscreen the player since we have `fullscreen` defined.
> Fix allowfullscreen warning in dev console

- Makefile
- bin/configure
- bin/serve_local_dev
- this splits the watch_and_build script in to the script that watches and the script that builds, so you can now do:
- `./bin/serve_local_dev`
- `./bin/watch_and_serve_local_dev`
> add make preamble and split build script

- source/includes/markdown/_06-rich-text.html.md
This PR changes the developer docs to reflect the new tags we'll make available in our initial rollout of Task Description enhancements.
> [ContEx] Update Developer Docs w/ Task Description enhancements

- source/includes/markdown/_12-audit-log.html.md
Assuming I did this correctly, this just adds our new workspace_baa_signed audit log event to the developer docs.
> Added workspace_baa_signed Audit Log event

- source/includes/markdown/_overview.html.md
- source/layouts/layout.erb
Adds headers for the OAS-generated material: API reference and schemas.
> Update sidebar headers

- source/includes/markdown/_audit-log.html.md
Adding newly created audit log event to the audit log event list. https://app.asana.com/0/1200172659753833/1203665883841779/f
> Add object_export_started event to audit logs

- source/includes/markdown/_rich-text.html.md
Removing these details about whitespace semantics since they will no longer apply to the Web UI.
A newline in the API represents a newline on web.
See this task for more details: https://app.asana.com/0/1153888223152336/1203332889573704/f
> Remove details about web UI blocks from API docs
